### ISSUE TITLE
Spawn Issue on Mac

### ISSUE THREAD

**Issue by mattdyedraws** [quiver-dev/tower-defense-godot4#2]
Having a spawning issue on the 1.0 alpha for Mac. Some units are stuck at the spawn point on the left. Occasionally a unit will "launch" toward the top of the screen and collide with other units (the tier 1 infantry in this screenshot is launching upward)

<img width="298" alt="Screen Shot 2022-09-29 at 9 49 10 AM" src="https://user-images.githubusercontent.com/114180731/193123991-9f6ac054-92c7-4f88-8564-0c015f7a9e34.png">

**Comment by Dodoveloper** [comment]
Seems working on latest Godot betas. Closing the issue for now
