### ISSUE TITLE
Load failed due to missing dependencies

### ISSUE THREAD

**Issue by godofgrunts** [quiver-dev/tower-defense-godot4#3]
Cloned [8615c7c](https://github.com/quiver-dev/tower-defense-godot4/commit/8615c7c67fda0e86dcac0e733208900d34511759) and tried to open the project. Received the following:

![image](https://user-images.githubusercontent.com/338843/199800848-9101e9b2-9a16-414c-b04f-dacd57859d0b.png)

Those two png files do appear to be corrupted.

```
file title.png
title.png: ASCII text
```

```
file mouse_diagram.png
mouse_diagram.png: ASCII text
```

**Comment by godofgrunts** [comment]
Just downloaded the [v1.0-beta2](https://github.com/quiver-dev/tower-defense-godot4/commit/61f2770779989311436b376f7716fc9b431a90fc) and got the same error.

**Comment by godofgrunts** [comment]
Okay weird. I just recloned and tried again and it worked fine...

That was weird.

**Comment by Dodoveloper** [comment]
Some weird errors regarding assets raise randomly sometimes. 
Not sure if this is due to LFS misconfiguration or the betas, let's see what happens with the stable release.
